name = "eba"
main = "src/index.ts"
compatibility_date = "2022-05-14"
kv_namespaces = [
  { binding = "EBA", id = "f055b00cfde7487ab3d1c450ba186bd2", preview_id = "b091d932d8474a4aba28ff6268bf0204" }
]